### ISSUE TITLE
Problems/Errors noted should link to the specific location of that problem in the json

### ISSUE THREAD

**Issue by jlow81** [GSA/json-schema-validator-web-component#1]
This is how the current tool works https://code.gov/#!/policy-guide/docs/compliance/inventory-code/tools/validate-schema and we should not lose that functionality since without it the usability is greatly decreased.

**Comment by saracope** [comment]
It looks like that is how the tool is currently working. The warnings at the bottom link to the line number of the problem. Any other info here?

<img width="822" alt="Screen Shot 2019-10-02 at 10 28 57 AM" src="https://user-images.githubusercontent.com/2197515/66052999-89ba6b80-e4ff-11e9-8b6b-59f3bee54fc8.png">

**Comment by jcastle-zz** [comment]
Deprecating repo for easier front-end management. Will eventually build capability into front-end after schema update around Aug. 2020.
