### ISSUE TITLE
Remove Blank Strings from JSON File

### ISSUE THREAD

**Issue by DanielJDufour** [GSA/json-schema-validator-web-component#2]
**Is your feature request related to a problem? Please describe.**
Agency would like some technical assistance removing blank strings from a JSON file

**Describe the solution you'd like**
Add a button to the top bar of the JSON Editor that says "remove optional fields with blank strings"

**Describe alternatives you've considered**
Could maybe include this in the sanitization process

**Additional context**
I've created an issue on the jsoneditor repo, which you can find here: https://github.com/josdejong/jsoneditor/issues/602

**Comment by jcastle-zz** [comment]
Deprecating repo for easier front-end management. Will eventually build capability into front-end after schema update around Aug. 2020.
